#!/usr/bin/env ruby

USERNAME = ENV.fetch('IDONETHIS_USERNAME')
TOKEN = ENV.fetch('IDONETHIS_TOKEN')
TEAM = ENV.fetch('IDONETHIS_TEAM')

API_ROOT = 'https://idonethis.com/api/v0.1'

if [USERNAME, TOKEN, TEAM].any?(&:empty?)
  help
  abort
end

require 'json'
require 'net/http'
require 'pp'

def help
  puts <<-EOF.gsub(/^.*#./, '')
    # Quick and dirty script for idonethis.
    # Requires follwing env variables:
    # - IDONETHIS_TEAM - team shortname (found in url)
    # - IDONETHIS_TOKEN - your idonethis api token
    # - IDONETHIS_USERNAME - your idonethis username
    # Usage:
    #  idone "Finished idone script" - will create a new done
    #  idone - will list yesterday and today
    #
EOF
end

def req(method: Net::HTTP::Get, path: '/dones/', params: {}, data: {})
  param_str = ['?', URI.encode_www_form(params)].join ''
  uri = URI.parse(API_ROOT + path + param_str)

  request = method.new uri
  request['Content-Type'] = 'application/json'
  request['Authorization'] = "Token #{TOKEN}"

  request.set_form_data data unless data.empty?

  resp = Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|
    http.request(request)
  end

  JSON.parse(resp.body)
end

def create_done(done_text, _is_goal = false)
  res = req(method: Net::HTTP::Post, data: { raw_text: done_text, team: TEAM })
  show_create(res)
end

def show_list(response)
  response['results'].map do |res|
    sigil = res['goal_completed'] ? '✔︎' : '╳'
    puts "#{sigil}\t#{res['markedup_text']}"
  end
end

def show_create(response)
  if response['ok']
    puts '✔︎ Ok'
  else
    puts 'Failed'
    pp response
  end
end

done_text = ARGV[0]

if ['-h', '-?', '--help'].include? done_text.strip.chomp
  help
  exit 0
end

create_done(done_text) unless done_text.nil? || done_text.empty?

puts '> Yesterday'
show_list req params: { done_date: 'yesterday', owner: USERNAME }
puts

puts '> Today'
show_list req params: { done_date: 'today', owner: USERNAME }
