#!/usr/bin/env ruby

require 'json'
require 'net/http'
require 'pp'

require 'optparse'

VERSION = '1.0.0'

HELP = <<-EOF
Tiny client for idonethis.com, v#{VERSION}

Requires follwing env variables:
  - IDONETHIS_TEAM - team shortname found in URL,
                     typically https://idonethis.com/cal/<shortname>/
  - IDONETHIS_TOKEN - your iDoneThis API token
                      https://idonethis.com/api/token
  - IDONETHIS_USERNAME - your iDoneThis username
                      https://idonethis.com/accounts/settings/account/

Usage:
   idone --text="[ ] get this done!" - create a new goal
   idone -t "got this done" - log a done
   idone --text="got it done" --id=2325 - update a done
   idone -c ID - complete a done
   idone --all - show all dones from team

Example:
  idone -t 'wrote idone client'
  idone -t '[ ] write readme' # returns id 121324
  idone -c 121324 # complete writing readme

Options:
EOF

USERNAME = ENV.fetch('IDONETHIS_USERNAME') do
  puts HELP
  abort 'IDONETHIS_USERNAME not set '
end

TOKEN = ENV.fetch('IDONETHIS_TOKEN') do
  puts HELP
  abort 'IDONETHIS_TOKEN not set'
end

TEAM = ENV.fetch('IDONETHIS_TEAM') do
  puts HELP
  abort 'IDONETHIS_TEAM not set'
end

API_ROOT = 'https://idonethis.com/api/v0.1'

def req(method: Net::HTTP::Get, path: '/dones/', params: {}, data: {})
  param_str = ['?', URI.encode_www_form(params)].join ''
  uri = URI.parse(API_ROOT + path + param_str)

  request = method.new uri
  request['Content-Type'] = 'application/json'
  request['Authorization'] = "Token #{TOKEN}"

  request.set_form_data data unless data.empty?

  resp = Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|
    http.request(request)
  end

  JSON.parse(resp.body)
end

def create_done(done_text)
  res = req(method: Net::HTTP::Post, data: { raw_text: done_text, team: TEAM })
  show_create(res)
end

def update_done(id, done_text)
  begin
    team_url = URI.parse(API_ROOT + '/teams/' + TEAM + '/').to_s
    res = req(method: Net::HTTP::Put,
              data: { raw_text: done_text, team: team_url },
              path: "/dones/#{id}/")

    puts "#{OK} Done"
  rescue => err

    puts "#{NOOK} Failed: #{err}"
  end
end

def complete_done(id)
  res = req(method: Net::HTTP::Get,
            path: "/dones/#{id}/")

  if res && res['results'] && res['results']['raw_text']
    text = res['result']['raw_text']

    update_done(id, text.sub(/\s*\[.*\]\s*/, ''))
  else
    puts "#{NOOK} Failed"
  end
end

def show_list(response)
  response['results'].map do |res|
    show_done(res)
  end
end

DONE_TEMPLATE = <<-EOF
%{sigil} | %{id} | %{owner} | %{text}
EOF

def show_done(done)
  sigil = done['goal_completed'] ? OK : GOAL
  puts DONE_TEMPLATE % { id: done['id'],
                         owner: done['owner'],
                         sigil: sigil,
                         text: done['raw_text'] }
end

def show_create(response)
  if response['ok']
    puts "#{OK} Ok"
  else
    puts "#{NOOK} Failed"
    pp response
  end
end

def parse_options
  options = { only_current_user: true }

  OptionParser.new do |opts|
    opts.banner = HELP
    opts.on('-tTEXT', '--text=TEXT', 'New to-be-done') do |text|
      options[:text] = text
    end

    opts.on('-a', '--all', 'Show dones from whole team') do
      options[:only_current_user] = false
    end

    opts.on('-y', '--yesterday', 'Show yesterday\'s dones') do
      options[:yesterday] = true
    end

    opts.on('-uID', '--update=ID', 'Update existing done') do |id|
      options[:id] = id
    end

    opts.on('-b', '--boring', 'Disable colors') do
      options[:boring] = true
    end

    opts.on('-cID', '--complete=ID', 'Complete goal') do |id|
      options[:text] = false
      options[:id] = false
      options[:complete_id] = id
    end
  end.parse!

  options
end

# ----------------------------------------------------

options = parse_options
if options[:boring]
  OK = '✓'
  GOAL = '☐'
  NOOK = '✗'
else
  reset = `tput sgr0`
  OK = "#{`tput setaf 4`}✓#{reset}"
  GOAL = "#{`tput setaf 6`}☐#{reset}"
  NOOK = "#{`tput setaf 5`}✗#{reset}"
end

if options[:complete_id]
  complete_done(options[:complete_id])
else

  done_text = options[:text]
  if done_text.to_s.size > 0
    id = options[:id]
    if id
      update_done(id, done_text)
    else # created
      create_done(done_text)
    end
  end
end

list_opts = {}
list_opts[:owner] = USERNAME if options[:only_current_user]

if options[:yesterday]
  puts '> Yesterday'
  show_list req params: { done_date: 'yesterday' }.merge(list_opts)
  puts
end

puts '> Today'
show_list req params: { done_date: 'today' }.merge(list_opts)
